### ISSUE TITLE
Flawed read/write benchmark read should return the String[]

### ISSUE THREAD

**Issue by arnaudroger** [osiegmar/JavaCsvBenchmarkSuite#1]
the result of the read and write method is not protected from dead code elimination as does not produce any side effect.
the read method should return the result of the read. 
and the NullWriter should pass the param of the write call to a Blackhole

**Comment by skjolber** [comment]
@osiegmar care to fix your benchmarks? I'll add my parser to your comparison once completed.

**Comment by osiegmar** [comment]
Thanks for your feedback. Just updated the project.
